name: 'Deploy a LAMP VM to Azure action'
description: 'This action helps create an Azure VM and deploy LAMP stack on it'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  client-id:
    description: 'Client id to login to azure'
    required: true
  tenant-id:
    description: 'Tenant id to login to azure'
    required: true
  subscription-id:
    description: 'Subscription id to be used with your az login'
    required: true
  resource-group-name:
    description: 'Resource group to deploy your resources to'
    required: true
  admin-username:
    description: 'Admin username to login to vm'
    required: true
  admin-password:
    description: 'Admin password to login to vm'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout master'
      uses: actions/checkout@v3
      
    - name: az cli login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: false

    - name: 'Accept Bitnami marketplace terms'
      shell: bash
      run: |
        az vm image terms accept --urn bitnami:lampstack:5-6:latest
        
    - name: 'Az deploy - LAMP on VM Bitnami'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ inputs.subscription-id }}
        resourceGroupName: ${{ inputs.resource-group-name }}
        template: https://raw.githubusercontent.com/vaibbavisk20/deploy_lamp_vm_azure/main/vm_template.json
        parameters: https://raw.githubusercontent.com/vaibbavisk20/deploy_lamp_vm_azure/main/vm_parameters.json
                    adminUsername=${{ inputs.admin-username }}
                    adminPassword=${{ inputs.admin-password }}
        failOnStdErr: false

    - name: Print specific values from JSON file
      shell: bash
      run: |
        # Replace 'path/to/your/json/file.json' and '.property.to.print' with your actual JSON file path and property path
        json_file=https://raw.githubusercontent.com/vaibbavisk20/deploy_lamp_vm_azure/main/vm_parameters.json
        property_to_print=".parameters.virtualMachineName.value"

        # Use jq to extract and print the desired property value
        result=$(jq -r "$property_to_print" "$json_file")

        echo "The value of $property_to_print is: $result"
